# git-credentials.yaml is a file that contains the credentials to access the git repository where the application configuration is stored. The credentials are stored in a Kubernetes secret named git-credentials in the argocd namespace. The secret contains the username and password required to access the git repository.

apiVersion: v1
kind: Secret
metadata:
 name: git-credentials
 namespace: argocd
type: Opaque
data:
 username: UHJpbmNlZG9zaGk=
 password: Sm9obmxlbm5vbkAxOTgw